CREATE DATABASE CONTROL_ASISTENCIA
GO
USE CONTROL_ASISTENCIA
GO
-- TABLA: COLABORADORES
CREATE TABLE COLABORADORES (
    IDCOLABORADOR INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    CORREO NVARCHAR(150) NOT NULL,
    TELEFONO NVARCHAR(20),
    ROL NVARCHAR(50) NOT NULL,
    ESTADO BIT NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL
);

CREATE TABLE USUARIO (
    IDCOLABORADOR INT PRIMARY KEY,
    CONTRASEÑA NVARCHAR(200) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    CONSTRAINT FK_Usuario_COLAB FOREIGN KEY (IDCOLABORADOR) REFERENCES COLABORADORES(IDCOLABORADOR)
);

-- TABLA: REGISTROSASISTENCIA
CREATE TABLE REGISTROSASISTENCIA (
    IDREGISTRO INT IDENTITY(1,1) PRIMARY KEY,
    IDCOLABORADOR INT NOT NULL,
    FECHA DATE NOT NULL,
    HORAENTRADA TIME NULL,
    HORASALIDA TIME NULL,
    IPREGISTRO NVARCHAR(50) NULL,
    MACADDRESS NVARCHAR(50) NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    CONSTRAINT FK_REGISTRO_COLAB FOREIGN KEY (IDCOLABORADOR) REFERENCES COLABORADORES(IDCOLABORADOR)
);

-- TABLA: TAREAS
CREATE TABLE TAREAS (
    IDTAREA INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE NVARCHAR(200) NOT NULL,
    DESCRIPCION NVARCHAR(MAX) NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL
);

-- TABLA: TAREASASIGNADAS
CREATE TABLE TAREASASIGNADAS (
    IDASIGNACION INT IDENTITY(1,1) PRIMARY KEY,
    IDCOLABORADOR INT NOT NULL,
    IDTAREA INT NOT NULL,
    FECHAASIGNACION DATETIME NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    CONSTRAINT FK_ASIG_COLAB FOREIGN KEY (IDCOLABORADOR) REFERENCES COLABORADORES(IDCOLABORADOR),
    CONSTRAINT FK_ASIG_TAREA FOREIGN KEY (IDTAREA) REFERENCES TAREAS(IDTAREA)
);

-- TABLA: DESCANSOS
CREATE TABLE DESCANSOS (
    IDDESCANSO INT IDENTITY(1,1) PRIMARY KEY,
    IDASIGNACION INT NOT NULL,
    TIPODESCANSO NVARCHAR(50) NOT NULL,
    HORAINICIO DATETIME NOT NULL,
    HORAFIN DATETIME NOT NULL,
    MOTIVO NVARCHAR(MAX) NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    CONSTRAINT FK_DESC_ASIG FOREIGN KEY (IDASIGNACION) REFERENCES TAREASASIGNADAS(IDASIGNACION)
);

-- TABLA: PERMISOS
CREATE TABLE PERMISOS (
    IDPERMISO INT IDENTITY(1,1) PRIMARY KEY,
    IDCOLABORADOR INT NOT NULL,
    FECHASOLICITUD DATETIME NOT NULL,
    FECHAINICIO DATETIME NOT NULL,
    FECHAFIN DATETIME NOT NULL,
    MOTIVO NVARCHAR(MAX) NULL,
    ESTADO NVARCHAR(50) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL,
    CONSTRAINT FK_PERM_COLAB FOREIGN KEY (IDCOLABORADOR) REFERENCES COLABORADORES(IDCOLABORADOR)
);

-- TABLA: BITACORA_ERRORES
CREATE TABLE BITACORA_ERRORES (
    IDERROR INT IDENTITY(1,1) PRIMARY KEY,
    MODULO NVARCHAR(250) NOT NULL,
    ERROR NVARCHAR(MAX) NOT NULL,
    FECHA_CREACION DATETIME NOT NULL DEFAULT GETDATE(),
    FECHA_ACTUALIZACION DATETIME NULL
);
