
CREATE OR ALTER PROCEDURE SP_Tarea_List_id
  @IDTAREA INT
AS
BEGIN
   SELECT 
          IDTAREA,
          NOMBRE,
          DESCRIPCION,
          ESTADO AS ESTADOTAREA,
          FECHA_INICIO_TAREA,
          FECHA_FIN_TAREA
     FROM TAREAS
    WHERE IDTAREA = @IDTAREA
END;
GO



CREATE OR ALTER PROCEDURE SP_List_Asignaciones
  @IDTAREA INT,
  @ID_COLABORADOR INT 
AS
BEGIN

    DECLARE @ROL_COLABORADOR VARCHAR(50);

    --Obtener el rol del colaborador
    SELECT @ROL_COLABORADOR = ROL 
    FROM COLABORADORES 
    WHERE IDCOLABORADOR = @ID_COLABORADOR;

    SELECT 
        T.IDTAREA,
        T.NOMBRE,
        T.DESCRIPCION,
        T.ESTADO AS ESTADOTAREA,
        T.FECHA_INICIO_TAREA,
        T.FECHA_FIN_TAREA,

        -- ASIGNACIONES
        TA.IDASIGNACION,
        TA.FECHAASIGNACION,
        TA.ESTADO AS ESTADO_ASIGNACION_TAREA,

        -- COLABORADOR
        CO.IDCOLABORADOR,
        CO.NOMBRE AS NOMBRE_COLABORADOR,
        CO.APELLIDO,
        CO.CORREO,
        CO.TELEFONO,
        CO.ROL,
        CO.ESTADO AS ESTADOCOLABORADOR

    FROM TAREAS T
    LEFT JOIN TAREASASIGNADAS TA 
        ON T.IDTAREA = TA.IDTAREA
    LEFT JOIN COLABORADORES CO 
        ON TA.IDCOLABORADOR = CO.IDCOLABORADOR
    WHERE TA.IDTAREA = @IDTAREA
END;
GO

