ALTER TABLE TAREASASIGNADAS ADD ESTADO VARCHAR(100) --COMPLETADAS / PENDIENTES 
GO

ALTER TABLE TAREAS ADD ESTADO VARCHAR(100) --ACTIVA / PENDIENTES 
GO

CREATE OR ALTER PROCEDURE SP_Asignacion_List
  @idColaborador INT = NULL,
  @idTarea       INT = NULL,
  @desde DATETIME = NULL,
  @hasta DATETIME = NULL
AS
BEGIN
  SET NOCOUNT ON;
  SELECT IDASIGNACION, IDCOLABORADOR, IDTAREA,
         FECHAASIGNACION, FECHA_CREACION, FECHA_ACTUALIZACION
  FROM TAREASASIGNADAS
  WHERE (@idColaborador IS NULL OR IDCOLABORADOR = @idColaborador)
    AND (@idTarea IS NULL OR IDTAREA = @idTarea)
    AND (@desde IS NULL OR FECHAASIGNACION >= @desde)
    AND (@hasta IS NULL OR FECHAASIGNACION <= @hasta);
END
GO


