--PASO 1
-- Añadir columnas útiles si todavía no existen
IF COL_LENGTH('dbo.BITACORA_ERRORES','PROCEDURE_NAME') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD PROCEDURE_NAME NVARCHAR(200) NULL;

IF COL_LENGTH('dbo.BITACORA_ERRORES','LINEA') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD LINEA INT NULL;

IF COL_LENGTH('dbo.BITACORA_ERRORES','ERROR_NUMBER') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD ERROR_NUMBER INT NULL;

IF COL_LENGTH('dbo.BITACORA_ERRORES','SEVERITY') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD SEVERITY INT NULL;

IF COL_LENGTH('dbo.BITACORA_ERRORES','STATE_ERROR') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD STATE_ERROR INT NULL;

IF COL_LENGTH('dbo.BITACORA_ERRORES','FECHA') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD FECHA DATETIME2 NOT NULL CONSTRAINT DF_BITACORA_ERRORES_FECHA DEFAULT SYSUTCDATETIME();
  -- Añadir columnas IP y OBSERVACIONES si no existen (idempotente)
IF COL_LENGTH('dbo.BITACORA_ERRORES','IP') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD IP NVARCHAR(50) NULL;

IF COL_LENGTH('dbo.BITACORA_ERRORES','OBSERVACIONES') IS NULL
  ALTER TABLE dbo.BITACORA_ERRORES ADD OBSERVACIONES NVARCHAR(250) NULL;
GO

GO

--PASO 2
-- Modificar el SP de LogError para que ahora reciba mas parametros
CREATE OR ALTER PROCEDURE dbo.SP_Bitacora_LogError
  @modulo        NVARCHAR(250),
  @errorMessage  NVARCHAR(MAX),
  @procedureName NVARCHAR(200) = NULL,
  @lineNum       INT = NULL,
  @errorNumber   INT = NULL,
  @severity      INT = NULL,
  @stateError    INT = NULL,
  @ip            NVARCHAR(50) = NULL,
  @observaciones NVARCHAR(250) = NULL
AS
BEGIN
  SET NOCOUNT ON;

  INSERT INTO dbo.BITACORA_ERRORES
    (MODULO, ERROR, PROCEDURE_NAME, LINEA, ERROR_NUMBER, SEVERITY, STATE_ERROR, IP, OBSERVACIONES, FECHA_CREACION, FECHA_ACTUALIZACION, FECHA)
  VALUES
    (@modulo, @errorMessage, COALESCE(@procedureName, ''), @lineNum, @errorNumber, @severity, @stateError, @ip, @observaciones, SYSUTCDATETIME(), SYSUTCDATETIME(), SYSUTCDATETIME());
END
GO

-- De aca pasamos a reemplazar la llamada del SP en cada SP que se hizo la llamada de este SP jajaja